export enum TaxTransactionType {
  SHIFT_OPEN = 'SHIFT_OPEN',
  X_REPORT = 'X_REPORT',
  Z_REPORT = 'Z_REPORT',
  PING = 'PING',
  RECEIPT = 'RECEIPT',
  LAST_RECEIPT = 'LAST_RECEIPT',
  GO_OFFLINE = 'GO_OFFLINE',
  ASK_OFFLINE_CODES = 'ASK_OFFLINE_CODES',
  GO_ONLINE = 'GO_ONLINE',
  DEL_LAST_RECEIPT = 'DEL_LAST_RECEIPT'
}
