export enum TaxReceiptType {
  SELL = 'SELL',
  RETURN = 'RETURN',
  SERVICE_IN = 'SERVICE_IN',
  SERVICE_OUT = 'SERVICE_OUT',
  SERVICE_CURRENCY = 'SERVICE_CURRENCY',
  CURRENCY_EXCHANGE = 'CURRENCY_EXCHANGE'
}
